// DO NOT EDIT. generated by github.com/tinywasm/orm

package devtui

import (
	"github.com/tinywasm/fmt"
)

func (m *ActionArgs) ModelName() string {
	return "action_args"
}

var _schemaActionArgs = []fmt.Field{
		{Name: "key", Type: fmt.FieldText},
		{Name: "value", Type: fmt.FieldText},
	}

func (m *ActionArgs) Schema() []fmt.Field { return _schemaActionArgs }

func (m *ActionArgs) Pointers() []any { return []any{&m.Key, &m.Value} }

func (m *ActionArgs) IsNil() bool { return m == nil }

func (m *ActionArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("key", m.Key)
	w.String("value", m.Value)
}

func (m *ActionArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("key"); ok { m.Key = v }
	if v, ok := r.String("value"); ok { m.Value = v }
	return nil
}

type ActionArgsList []*ActionArgs

func (s *ActionArgsList) Schema() []fmt.Field { return nil }
func (s *ActionArgsList) Pointers() []any     { return nil }
func (s *ActionArgsList) Len() int             { return len(*s) }
func (s *ActionArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *ActionArgsList) Append() fmt.Fielder  { v := &ActionArgs{}; *s = append(*s, v); return v }
func (s *ActionArgsList) IsNil() bool          { return s == nil }
func (s *ActionArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *ActionArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

