package devtui

// GetLogsArgs defines arguments for the app_get_logs tool.
// ormc:formonly
type GetLogsArgs struct {
	Section string `input:"optional"`
}

// Schema will be generated by ormc.
func (a *GetLogsArgs) Schema() string { return "" }
